### ISSUE TITLE
Cart Backend

### ISSUE THREAD

**Issue by AhmedHamdan54** [The-POS/The-POS-Flutter#23]

**Comment by AhmedHamdan54** [comment]
Yes we can end this issue if we just add the delete function and if there is an option to be shown in the three dots 
![image](https://user-images.githubusercontent.com/33401474/139533183-d3c7c3e9-d2db-43ed-8d44-d51446f95642.png)

I want to suggest something, why don't we do a swipe to option item? I think it will be cleaner and we will have a better UX.
We can do that easily using this package https://github.com/letsar/flutter_slidable
What do you think @ServeMe ?

**Comment by ServeMe** [comment]
@AhmedHamdan54 I do encourage that for mobile and tablet but definitely not for web
So I think it will be good to keep it that way
