### ISSUE TITLE
How to setup a working local copy of this project?

### ISSUE THREAD

**Issue by shujaatak** [The-POS/The-POS-Flutter#38]
Although The-POS-Flutter seems amazing and definitely one would wish to contribute to this project but there is no documentation in the readme file about setting up a working copy of this project in one's local machine for testing and development.

It would be a lot helpful if you please provide detailed step by step instructions about how to setup a working copy of this project on local machine.

**Comment by shujaatak** [comment]
The reason for asking the question is that when i build and run The-POS-Flutter project, the app does not load any products. Is it normal or is there any bug or setting issue?

**Comment by ServeMe** [comment]
Hi @shujaatak the project builds on the idea of API First Approach so you can find the Open API spec in [here](https://thepos.stoplight.io/docs/thepos/YXBpOjI0MjY1NjUy-pos) if you want to add it to another system you need to implement the API on this system
 Anyway, for testing purposes, you can change the option `enableFaker` in [config file](https://github.com/The-POS/The-POS-Flutter/blob/d7c01669c8dcccd9c112de50b8f9f31a38670407/lib/core/config.dart#L4) to true

**Comment by shujaatak** [comment]
> Hi @shujaatak the project builds on the idea of API First Approach so you can find the Open API spec in [here](https://thepos.stoplight.io/docs/thepos/YXBpOjI0MjY1NjUy-pos) if you want to add it to another system you need to implement the API on this system Anyway, for testing purposes, you can change the option `enableFaker` in [config file](https://github.com/The-POS/The-POS-Flutter/blob/d7c01669c8dcccd9c112de50b8f9f31a38670407/lib/core/config.dart#L4) to true

@ServeMe Wow, such a nice and useful answer! Thank you so much brother!
