### ISSUE TITLE
Filter product by categories

### ISSUE THREAD

**Issue by AhmedHamdan54** [The-POS/The-POS-Flutter#41]
**Issue Requirements**
The user can filter items based on their category.

**API Documentation**
Check the GET METHOD  `Get Product Categories` and check `category` field in `Products` repository.
Endpoint: `/api/v2/product-categories`

**Mobile Design**
![image](https://user-images.githubusercontent.com/33401474/143686823-9134f48b-a4e1-4804-ae0e-c1e47e88d842.png)

**Tablet and Web Design**
![image](https://user-images.githubusercontent.com/33401474/143686949-c32ccd08-a98a-4b10-ae17-a77541f30e9a.png)

**Comment by ServeMe** [comment]
@HassanBalousha is this finished?

**Comment by HassanBalousha** [comment]
Yes

**Comment by ServeMe** [comment]
OK thank you and please for the next PR connect it to its issue
