### ISSUE TITLE
Create new costumer

### ISSUE THREAD

**Issue by AhmedHamdan54** [The-POS/The-POS-Flutter#43]
**Issue Requirements**
The user can create a new customer for the invoice

**API Documentation**
Check the POST METHOD  `Create New Customer`.
Endpoint: `/api/v2/costumers`

**Comment by DoaaNassar1995dbnassar** [comment]
explain issue

**Comment by ServeMe** [comment]
This is a modification on the feature cart you can start from there
You will find two presentation layers one for mobile and another for web here is the line for [web](https://github.com/The-POS/The-POS-Flutter/blob/c409e5250f9acebc4d235acffced7bacd77f37bf/lib/features/carts/presentation/views/web/cart_view.dart#L69)
modify the view to follow up with the designs -you can find the links design in the description of this repo or in the first note in project v2-
I admire you to follow the code structure written before and if you need more help let me know
