### ISSUE TITLE
Create product component

### ISSUE THREAD

**Issue by alaa-alsalehi** [The-POS/The-POS-flutter#7]
Our design shows similarities in some areas I suggest starting to create these as components
The first component I suggest creating is a `Product Component`
as shown in the design a product has a name, price, image -optional-, sales price -optional- and availability in stock
A component in ThePOS need to be:

- support RTL and LTR
- support mobile and web flutter version

![image](https://user-images.githubusercontent.com/1716129/137403665-5680d2c9-7d77-4349-a139-c6131cbdfc94.png)

**Comment by ServeMe** [comment]
@AhmedHamdan54 check this please if it is a good start let us go ahead and create a similar tasks
